services:
  postgres:
    image: postgres:16.1-alpine
    # env_file:
    #   - ./server/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: lendo
    volumes:
      - lendo:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    # env_file:
    #   - ./server/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/lendo
      PORT: 3000
    ports:
      - "3000:3000" 
    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  lendo:
